// ============================================================
// StateCraft — Multi-Format Code Generator
// Generates production-ready code from state machines
// Formats: XState v5, React useReducer, TypeScript Switch, Zustand
// ============================================================

export class CodeGenerator {
  /**
   * Generate code in the specified format
   * @param {import('./stateMachine.js').StateMachine} machine
   * @param {'xstate'|'reducer'|'typescript'|'zustand'} format
   * @returns {{ code: string, language: string }}
   */
  generate(machine, format) {
    switch (format) {
      case 'xstate': return this.generateXState(machine);
      case 'reducer': return this.generateReducer(machine);
      case 'typescript': return this.generateTypeScript(machine);
      case 'zustand': return this.generateZustand(machine);
      case 'mermaid': return this.generateMermaid(machine);
      case 'json': return this.generateJSON(machine);
      default: return { code: '// Unknown format', language: 'javascript' };
    }
  }

  // ---- XState v5 ----

  generateXState(machine) {
    const id = this.toCamelCase(machine.id);
    const states = machine.getStateNames();
    const events = machine.getAllEvents();

    let code = `// ${this.toTitleCase(machine.id)} State Machine — XState v5\n`;
    code += `// Generated by StateCraft\n\n`;
    code += `import { createMachine } from 'xstate';\n\n`;

    // Type definitions
    code += `// Type-safe event definitions\n`;
    code += `type ${this.toPascalCase(id)}Event =\n`;
    code += events.map(e => `  | { type: '${e.toUpperCase()}' }`).join('\n');
    code += `;\n\n`;

    code += `export const ${id}Machine = createMachine({\n`;
    code += `  id: '${id}',\n`;
    code += `  initial: '${machine.initialState || states[0]}',\n`;
    code += `  states: {\n`;

    for (const name of states) {
      const stateNode = machine.getState(name);
      const outgoing = machine.getTransitionsFrom(name);

      code += `    ${name}: {\n`;

      // Type tag
      if (stateNode?.type === 'final') {
        code += `      type: 'final',\n`;
      }

      if (outgoing.length > 0) {
        code += `      on: {\n`;

        // Group by event
        const eventMap = new Map();
        for (const t of outgoing) {
          if (!eventMap.has(t.event)) eventMap.set(t.event, []);
          eventMap.get(t.event).push(t);
        }

        for (const [event, transitions] of eventMap) {
          if (transitions.length === 1 && !transitions[0].guard) {
            code += `        ${event.toUpperCase()}: '${transitions[0].to}',\n`;
          } else {
            code += `        ${event.toUpperCase()}: [\n`;
            for (const t of transitions) {
              if (t.guard) {
                code += `          { target: '${t.to}', guard: '${t.guard}' },\n`;
              } else {
                code += `          { target: '${t.to}' },\n`;
              }
            }
            code += `        ],\n`;
          }
        }

        code += `      },\n`;
      }

      code += `    },\n`;
    }

    code += `  },\n`;
    code += `});\n`;

    return { code, language: 'TypeScript' };
  }

  // ---- React useReducer ----

  generateReducer(machine) {
    const id = this.toCamelCase(machine.id);
    const pascalId = this.toPascalCase(id);
    const states = machine.getStateNames();
    const events = machine.getAllEvents();

    let code = `// ${this.toTitleCase(machine.id)} — React useReducer Pattern\n`;
    code += `// Generated by StateCraft\n\n`;
    code += `import { useReducer } from 'react';\n\n`;

    // State type
    code += `// State enum\n`;
    code += `const ${pascalId}State = {\n`;
    for (const s of states) {
      code += `  ${s.toUpperCase()}: '${s}',\n`;
    }
    code += `};\n\n`;

    // Action types
    code += `// Action types\n`;
    code += `const ${pascalId}Action = {\n`;
    for (const e of events) {
      code += `  ${e.toUpperCase()}: '${e.toUpperCase()}',\n`;
    }
    code += `};\n\n`;

    // Initial state
    code += `const initialState = {\n`;
    code += `  status: ${pascalId}State.${(machine.initialState || states[0]).toUpperCase()},\n`;
    code += `  history: [],\n`;
    code += `};\n\n`;

    // Reducer
    code += `function ${id}Reducer(state, action) {\n`;
    code += `  switch (state.status) {\n`;

    for (const name of states) {
      const outgoing = machine.getTransitionsFrom(name);
      if (outgoing.length === 0) continue;

      code += `    case ${pascalId}State.${name.toUpperCase()}:\n`;
      code += `      switch (action.type) {\n`;

      for (const t of outgoing) {
        code += `        case ${pascalId}Action.${t.event.toUpperCase()}:\n`;
        code += `          return {\n`;
        code += `            ...state,\n`;
        code += `            status: ${pascalId}State.${t.to.toUpperCase()},\n`;
        code += `            history: [...state.history, { from: '${name}', event: '${t.event}', to: '${t.to}' }],\n`;
        code += `          };\n`;
      }

      code += `        default:\n`;
      code += `          return state; // Unhandled event — stay in current state\n`;
      code += `      }\n`;
    }

    code += `    default:\n`;
    code += `      return state;\n`;
    code += `  }\n`;
    code += `}\n\n`;

    // Custom hook
    code += `// Custom hook\n`;
    code += `export function use${pascalId}() {\n`;
    code += `  const [state, dispatch] = useReducer(${id}Reducer, initialState);\n\n`;
    code += `  return {\n`;
    code += `    status: state.status,\n`;
    code += `    history: state.history,\n`;

    for (const e of events) {
      code += `    ${this.toCamelCase(e)}: () => dispatch({ type: ${pascalId}Action.${e.toUpperCase()} }),\n`;
    }

    code += `  };\n`;
    code += `}\n`;

    return { code, language: 'JavaScript' };
  }

  // ---- TypeScript Enum + Switch ----

  generateTypeScript(machine) {
    const id = this.toCamelCase(machine.id);
    const pascalId = this.toPascalCase(id);
    const states = machine.getStateNames();
    const events = machine.getAllEvents();

    let code = `// ${this.toTitleCase(machine.id)} — TypeScript State Machine\n`;
    code += `// Generated by StateCraft\n\n`;

    // State enum
    code += `enum ${pascalId}State {\n`;
    for (const s of states) {
      code += `  ${this.toPascalCase(s)} = '${s}',\n`;
    }
    code += `}\n\n`;

    // Event enum
    code += `enum ${pascalId}Event {\n`;
    for (const e of events) {
      code += `  ${this.toPascalCase(e)} = '${e}',\n`;
    }
    code += `}\n\n`;

    // Transition type
    code += `interface ${pascalId}Transition {\n`;
    code += `  from: ${pascalId}State;\n`;
    code += `  event: ${pascalId}Event;\n`;
    code += `  to: ${pascalId}State;\n`;
    code += `}\n\n`;

    // Machine class
    code += `class ${pascalId}Machine {\n`;
    code += `  private currentState: ${pascalId}State;\n`;
    code += `  private history: ${pascalId}Transition[] = [];\n\n`;

    code += `  constructor() {\n`;
    code += `    this.currentState = ${pascalId}State.${this.toPascalCase(machine.initialState || states[0])};\n`;
    code += `  }\n\n`;

    code += `  get state(): ${pascalId}State {\n`;
    code += `    return this.currentState;\n`;
    code += `  }\n\n`;

    // Transition method
    code += `  send(event: ${pascalId}Event): ${pascalId}State {\n`;
    code += `    const nextState = this.getNextState(this.currentState, event);\n`;
    code += `    if (nextState !== null) {\n`;
    code += `      this.history.push({ from: this.currentState, event, to: nextState });\n`;
    code += `      this.currentState = nextState;\n`;
    code += `    }\n`;
    code += `    return this.currentState;\n`;
    code += `  }\n\n`;

    // Transition table
    code += `  private getNextState(state: ${pascalId}State, event: ${pascalId}Event): ${pascalId}State | null {\n`;
    code += `    switch (state) {\n`;

    for (const name of states) {
      const outgoing = machine.getTransitionsFrom(name);
      if (outgoing.length === 0) continue;

      code += `      case ${pascalId}State.${this.toPascalCase(name)}:\n`;
      code += `        switch (event) {\n`;

      for (const t of outgoing) {
        code += `          case ${pascalId}Event.${this.toPascalCase(t.event)}: return ${pascalId}State.${this.toPascalCase(t.to)};\n`;
      }

      code += `          default: return null;\n`;
      code += `        }\n`;
    }

    code += `      default: return null;\n`;
    code += `    }\n`;
    code += `  }\n`;
    code += `}\n\n`;

    code += `export default ${pascalId}Machine;\n`;

    return { code, language: 'TypeScript' };
  }

  // ---- Zustand Store ----

  generateZustand(machine) {
    const id = this.toCamelCase(machine.id);
    const pascalId = this.toPascalCase(id);
    const states = machine.getStateNames();
    const events = machine.getAllEvents();

    let code = `// ${this.toTitleCase(machine.id)} — Zustand State Machine Store\n`;
    code += `// Generated by StateCraft\n\n`;
    code += `import { create } from 'zustand';\n\n`;

    // State constants
    code += `const STATES = {\n`;
    for (const s of states) {
      code += `  ${s.toUpperCase()}: '${s}',\n`;
    }
    code += `};\n\n`;

    // Transition map
    code += `// Transition lookup table\n`;
    code += `const transitions = {\n`;
    for (const name of states) {
      const outgoing = machine.getTransitionsFrom(name);
      if (outgoing.length === 0) continue;

      code += `  [STATES.${name.toUpperCase()}]: {\n`;
      for (const t of outgoing) {
        code += `    '${t.event}': STATES.${t.to.toUpperCase()},\n`;
      }
      code += `  },\n`;
    }
    code += `};\n\n`;

    // Store
    code += `export const use${pascalId}Store = create((set, get) => ({\n`;
    code += `  // Current state\n`;
    code += `  status: STATES.${(machine.initialState || states[0]).toUpperCase()},\n\n`;
    code += `  // Transition history\n`;
    code += `  history: [],\n\n`;

    code += `  // Generic send function\n`;
    code += `  send: (event) => {\n`;
    code += `    const { status, history } = get();\n`;
    code += `    const stateTransitions = transitions[status];\n`;
    code += `    if (stateTransitions && stateTransitions[event]) {\n`;
    code += `      set({\n`;
    code += `        status: stateTransitions[event],\n`;
    code += `        history: [...history, { from: status, event, to: stateTransitions[event], timestamp: Date.now() }],\n`;
    code += `      });\n`;
    code += `    }\n`;
    code += `  },\n\n`;

    // Convenience methods for each event
    code += `  // Convenience methods\n`;
    for (const e of events) {
      code += `  ${this.toCamelCase(e)}: () => get().send('${e}'),\n`;
    }

    code += `\n  // Reset to initial state\n`;
    code += `  reset: () => set({ status: STATES.${(machine.initialState || states[0]).toUpperCase()}, history: [] }),\n`;

    code += `\n  // Check if event is valid in current state\n`;
    code += `  canSend: (event) => {\n`;
    code += `    const stateTransitions = transitions[get().status];\n`;
    code += `    return !!(stateTransitions && stateTransitions[event]);\n`;
    code += `  },\n`;

    code += `}));\n`;

    return { code, language: 'JavaScript' };
  }

  // ---- Mermaid Export ----

  generateMermaid(machine) {
    return { code: machine.toMermaid(), language: 'Mermaid' };
  }

  // ---- JSON Export ----

  generateJSON(machine) {
    return { code: JSON.stringify(machine.toJSON(), null, 2), language: 'JSON' };
  }

  // ---- Syntax Highlighter (simple token-based) ----

  highlight(code, language) {
    const KEYWORDS = new Set(['import', 'export', 'from', 'const', 'let', 'var', 'function', 'class',
      'return', 'switch', 'case', 'default', 'if', 'else', 'new', 'this', 'get', 'set',
      'private', 'type', 'interface', 'enum', 'extends', 'implements', 'readonly',
      'void', 'null', 'undefined', 'true', 'false', 'typeof', 'instanceof']);

    // Split code into lines for easier processing
    const lines = code.split('\n');
    const highlightedLines = [];

    for (const line of lines) {
      // Handle full-line comment
      const commentIdx = line.indexOf('//');
      let codePart = line;
      let commentPart = '';

      if (commentIdx !== -1) {
        // Check if // is inside a string
        const beforeComment = line.substring(0, commentIdx);
        const singleQuotes = (beforeComment.match(/'/g) || []).length;
        const doubleQuotes = (beforeComment.match(/"/g) || []).length;
        if (singleQuotes % 2 === 0 && doubleQuotes % 2 === 0) {
          codePart = line.substring(0, commentIdx);
          commentPart = line.substring(commentIdx);
        }
      }

      // Tokenize the code part
      let result = '';
      let i = 0;
      while (i < codePart.length) {
        const ch = codePart[i];

        // String literals (single or double quoted)
        if (ch === "'" || ch === '"') {
          const quote = ch;
          let str = quote;
          i++;
          while (i < codePart.length && codePart[i] !== quote) {
            if (codePart[i] === '\\' && i + 1 < codePart.length) {
              str += codePart[i] + codePart[i + 1];
              i += 2;
            } else {
              str += codePart[i];
              i++;
            }
          }
          if (i < codePart.length) { str += codePart[i]; i++; }
          result += `<span class="hl-str">${this.escapeHtml(str)}</span>`;
          continue;
        }

        // Numbers
        if (/\d/.test(ch) && (i === 0 || !/[a-zA-Z_]/.test(codePart[i - 1]))) {
          let num = '';
          while (i < codePart.length && /[\d.]/.test(codePart[i])) {
            num += codePart[i];
            i++;
          }
          result += `<span class="hl-num">${num}</span>`;
          continue;
        }

        // Identifiers and keywords
        if (/[a-zA-Z_$]/.test(ch)) {
          let word = '';
          while (i < codePart.length && /[a-zA-Z0-9_$]/.test(codePart[i])) {
            word += codePart[i];
            i++;
          }
          if (KEYWORDS.has(word)) {
            result += `<span class="hl-kw">${word}</span>`;
          } else if (/^[A-Z]/.test(word) && word.length > 1) {
            result += `<span class="hl-type">${word}</span>`;
          } else {
            result += this.escapeHtml(word);
          }
          continue;
        }

        // Operators and punctuation
        result += this.escapeHtml(ch);
        i++;
      }

      // Append comment part
      if (commentPart) {
        result += `<span class="hl-cm">${this.escapeHtml(commentPart)}</span>`;
      }

      highlightedLines.push(result);
    }

    return highlightedLines.join('\n');
  }

  escapeHtml(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  // ---- String Utilities ----

  toCamelCase(str) {
    return str.replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[A-Z]/, c => c.toLowerCase());
  }

  toPascalCase(str) {
    return str.replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, c => c.toUpperCase());
  }

  toTitleCase(str) {
    return str.replace(/[-_]/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }
}
